name: R-CI-CodeCoverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CI-CodeCoverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)

      - name: Install Codecov dependencies
        run: |
          install.packages("covr")

      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests")'

      - name: Run code coverage
        run: |
          Rscript -e 'covr::codecov(token = Sys.getenv("CODECOV_TOKEN"))'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

