name: R-CI-CodeCoverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CI-CodeCoverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)

      - name: Install Codecov dependencies
        run: |
          install.packages("covr")

      - name: Verify test directory exists
        run: |
          if [ ! -d "tests" ]; then echo "Directory 'tests' does not exist"; exit 1; fi

      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests")'

      - name: Run code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          Rscript -e 'covr::codecov()'

      - name: Upload Coverage Report
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
